# Generated by Django 3.1.2 on 2020-10-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20201016_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
        migrations.AddField(
            model_name='player',
            name='developers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
