# Generated by Django 3.1.2 on 2020-10-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201016_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='playerNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
